services:
  addhash.user.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\UserCreateService
    public: true
    arguments: ['@addhash.authentication.adapter.open.host', '@addhash.user.info.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\UserCreateService: '@addhash.user.create.service'

  App\AddHash\AdminPanel\Domain\User\Services\UserCreateServiceInterface: '@addhash.user.create.service'

  addhash.user.get.authentication.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\UserGetAuthenticationService
    public: true
    arguments: ['@addhash.authentication.adapter.open.host', '@addhash.user.info.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\UserGetAuthenticationService: '@addhash.user.get.authentication.service'

  App\AddHash\AdminPanel\Domain\User\Services\UserGetAuthenticationServiceInterface: '@addhash.user.get.authentication.service'

  addhash.user.info.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\User\UserRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\User\UserRepository: '@addhash.user.info.repository'

  App\AddHash\AdminPanel\Domain\User\UserRepositoryInterface: '@addhash.user.info.repository'

  addhash.user.wallet.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\User\UserWalletRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\User\UserWalletRepository: '@addhash.user.wallet.repository'

  App\AddHash\AdminPanel\Domain\User\UserWalletRepositoryInterface: '@addhash.user.wallet.repository'

  addhash.user.miner.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\User\Miner\UserMinerRepository
    public: true
    arguments: ['@addhash.cache']
  App\AddHash\AdminPanel\Infrastructure\Repository\User\Miner\UserMinerRepository: '@addhash.user.miner.repository'

  App\AddHash\AdminPanel\Domain\User\Miner\UserMinerRepositoryInterface: '@addhash.user.miner.repository'

  addhash.user.vote.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Store\Product\StoreProductUserVoteRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Store\Product\StoreProductUserVoteRepository: '@addhash.user.vote.repository'

  App\AddHash\AdminPanel\Domain\Store\Product\StoreProductUserVoteRepositoryInterface: '@addhash.user.vote.repository'

  addhash.user.account.settings.general.information.update.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\GeneralInformationUpdateService
    public: true
    arguments: ['@addhash.authentication.adapter.open.host', '@addhash.user.get.authentication.service', '@addhash.user.info.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\GeneralInformationUpdateService: '@addhash.user.account.settings.general.information.update.service'

  App\AddHash\AdminPanel\Domain\User\Services\AccountSettings\GeneralInformationUpdateServiceInterface: '@addhash.user.account.settings.general.information.update.service'

  addhash.user.account.settings.general.information.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\GeneralInformationGetService
    public: true
    arguments: ['@addhash.authentication.adapter.open.host', '@addhash.user.get.authentication.service']
  App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\GeneralInformationGetService: '@addhash.user.account.settings.general.information.get.service'

  App\AddHash\AdminPanel\Domain\User\Services\AccountSettings\GeneralInformationGetServiceInterface: '@addhash.user.account.settings.general.information.get.service'

  addhash.user.account.settings.password.update.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\PasswordUpdateService
    public: true
    arguments: ['@addhash.authentication.adapter.open.host']
  App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\PasswordUpdateService: '@addhash.user.account.settings.password.update.service'

  App\AddHash\AdminPanel\Domain\User\Services\AccountSettings\PasswordUpdateServiceInterface: '@addhash.user.account.settings.password.update.service'

  addhash.user.account.settings.wallet.update.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\WalletUpdateService
    public: true
    arguments: ['@addhash.user.wallet.repository', '@addhash.wallet.repository', '@addhash.wallet.type.repository', '@addhash.user.get.authentication.service']
  App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\WalletUpdateService: '@addhash.user.account.settings.wallet.update.service'

  App\AddHash\AdminPanel\Domain\User\Services\AccountSettings\WalletUpdateServiceInterface: '@addhash.user.account.settings.wallet.update.service'

  addhash.user.account.settings.wallet.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\WalletGetService
    public: true
    arguments: ['@addhash.user.get.authentication.service', '@addhash.user.wallet.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\WalletGetService: '@addhash.user.account.settings.wallet.get.service'

  App\AddHash\AdminPanel\Domain\User\Services\AccountSettings\WalletGetServiceInterface: '@addhash.user.account.settings.wallet.get.service'

  addhash.user.account.settings.wallet.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\WalletCreateService
    public: true
    arguments: ['@addhash.wallet.repository', '@addhash.user.wallet.repository', '@addhash.wallet.type.repository', '@addhash.user.get.authentication.service']
  App\AddHash\AdminPanel\Infrastructure\Services\User\AccountSettings\WalletCreateService: '@addhash.user.account.settings.wallet.create.service'

  App\AddHash\AdminPanel\Domain\User\Services\AccountSettings\WalletCreateServiceInterface: '@addhash.user.account.settings.wallet.create.service'

  addhash.user.order.miner.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\User\Order\Miner\UserOrderMinerRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\User\Order\Miner\UserOrderMinerRepository: '@addhash.user.order.miner.repository'

  App\AddHash\AdminPanel\Domain\User\Order\UserOrderMinerRepositoryInterface: '@addhash.user.order.miner.repository'

  addhash.user.order.miner.create.service:
    class:  App\AddHash\AdminPanel\Infrastructure\Services\User\Order\Miner\CreateUserOrderMinerService
    public: true
    arguments: ['@addhash.store.order.repository', '@addhash.user.order.miner.repository', '@addhash.miner.repository', '@addhash.miner.stock.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Order\Miner\CreateUserOrderMinerService: '@addhash.user.order.miner.create.service'

  App\AddHash\AdminPanel\Domain\User\Services\Order\Miner\CreateUserOrderMinerServiceInterface: '@addhash.user.order.miner.create.service'

  addhash.user.miner.control.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\MinerControlGetService
    public: true
    arguments: ['@addhash.user.get.authentication.service','@addhash.user.miner.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\MinerControlGetService: '@addhash.user.miner.control.get.service'

  App\AddHash\AdminPanel\Domain\User\Services\MinerControlGetServiceInterface: '@addhash.user.miner.control.get.service'

  addhash.user.order.history.list.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Order\History\UserOrderHistoryListService
    public: true
    arguments: ['@addhash.user.get.authentication.service', '@addhash.store.order.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Order\History\UserOrderHistoryListService: '@addhash.user.order.history.list.service'

  App\AddHash\AdminPanel\Domain\User\Services\Order\History\UserOrderHistoryListServiceInterface: '@addhash.user.order.history.list.service'

  addhash.user.order.history.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Order\History\UserOrderHistoryGetService
    public: true
    arguments: ['@addhash.user.get.authentication.service', '@addhash.store.order.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Order\History\UserOrderHistoryGetService: '@addhash.user.order.history.get.service'

  App\AddHash\AdminPanel\Domain\User\Services\Order\History\UserOrderHistoryGetServiceInterface: '@addhash.user.order.history.get.service'

  addhash.user.miner.control.rig.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\Rig\UserMinerControlRigCreateService
    public: true
    arguments: ['@addhash.user.get.authentication.service']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\Rig\UserMinerControlRigCreateService: '@addhash.user.miner.control.rig.create.service'

  App\AddHash\AdminPanel\Domain\User\Services\Miner\Rig\UserMinerControlRigCreateServiceInterface: '@addhash.user.miner.control.rig.create.service'

  addhash.user.notification.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\User\Notification\UserNotificationRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\User\Notification\UserNotificationRepository: '@addhash.user.notification.repository'

  App\AddHash\AdminPanel\Domain\User\Notification\UserNotificationRepositoryInterface: '@addhash.user.notification.repository'

  addhash.user.notification.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Notification\GetUserNotificationService
    public: true
    arguments: ['@addhash.user.get.authentication.service', '@addhash.user.notification.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Notification\GetUserNotificationService: '@addhash.user.notification.get.service'

  App\AddHash\AdminPanel\Domain\User\Services\Notification\GetUserNotificationServiceInterface: '@addhash.user.notification.get.service'

  addhash.user.notification.send.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Notification\SendUserNotificationService
    public: true
    arguments: ['@addhash.user.notification.repository', '@old_sound_rabbit_mq.userNotification_producer']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Notification\SendUserNotificationService: '@addhash.user.notification.send.service'

  App\AddHash\AdminPanel\Domain\User\Services\Notification\SendUserNotificationServiceInterface: '@addhash.user.notification.send.service'

  addhash.user.notification.markread.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Notification\MarkAsReadNotificationService
    public: true
    arguments: ['@addhash.user.notification.repository', '@addhash.user.get.authentication.service']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Notification\MarkAsReadNotificationService: '@addhash.user.notification.markread.service'

  App\AddHash\AdminPanel\Domain\User\Services\Notification\MarkAsReadNotificationServiceInterface: '@addhash.user.notification.markread.service'

  addhash.user.miner.pool.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\Pool\UserMinerPoolGetService
    public: true
    arguments: ['@addhash.user.get.authentication.service', '@addhash.user.order.miner.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\Pool\UserMinerPoolGetService: '@addhash.user.miner.pool.get.service'

  App\AddHash\AdminPanel\Domain\User\Services\Miner\Pool\UserMinerPoolGetServiceInterface: '@addhash.user.miner.pool.get.service'

  addhash.user.miner.pool.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\Pool\UserMinerPoolCreateService
    public: true
    arguments: ['@addhash.user.get.authentication.service', '@addhash.user.order.miner.repository', '@addhash.miner.allowed.url.repository', '@addhash.miner.stock.pool.repository', '%env(PATH_RSA_PUBLIC_KEY)%', '%env(PATH_RSA_PRIVATE_KEY)%', '%env(DIR_CONFIG_POOLS)%']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\Pool\UserMinerPoolCreateService: '@addhash.user.miner.pool.create.service'

  App\AddHash\AdminPanel\Domain\User\Services\Miner\Pool\UserMinerPoolCreateServiceInterface: '@addhash.user.miner.pool.create.service'

  addhash.un.reserve.miner.stock.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\UnReserveMinerStockService
    public: true
    arguments: ['@addhash.user.order.miner.repository', '@addhash.miner.stock.repository', '@addhash.user.notification.send.service', '@addhash.authentication.adapter.open.host', '@addhash.mail.send']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\UnReserveMinerStockService: '@addhash.un.reserve.miner.stock.service'

  App\AddHash\AdminPanel\Domain\User\Miner\UnReserveMinerStockServiceInterface: '@addhash.un.reserve.miner.stock.service'

  addhash.end.rent.period.miner.stock.notification.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\EndRentPeriodMinerStockNotificationService
    public: true
    arguments: ['@addhash.user.order.miner.repository', '@addhash.user.notification.send.service', '@addhash.authentication.adapter.open.host', '@addhash.mail.send']
  App\AddHash\AdminPanel\Infrastructure\Services\User\Miner\EndRentPeriodMinerStockNotificationService: '@addhash.end.rent.period.miner.stock.notification.service'

  App\AddHash\AdminPanel\Domain\User\Miner\EndRentPeriodMinerStockNotificationServiceInterface: '@addhash.end.rent.period.miner.stock.notification.service'