version: '3'
services:
    mysql:
      image: mariadb
      ports:
        - "${MYSQL_LOCAL_PORT}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      volumes:
        - ./var/data/mysql:/var/lib/mysql:cached
        - ./docker/mysql/conf.d:/etc/mysql/conf.d/:cached
      networks:
        - equipmentscrm


    redis:
      image: redis
      ports:
        - "${REDIS_LOCAL_PORT}:6379"
      networks:
        - equipmentscrm

    rabbitmq:
      image: rabbitmq:latest
      ports:
        - "${RABBIT_ADMIN_LOCAL_PORT}:15672"
        - "${RABBIT_LOCAL_PORT}:5672"
      volumes:
        - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:cached
      networks:
        - equipmentscrm


    nginx:
        image: nginx
        container_name: nginx
        hostname: ${NGINX_HOST}
        restart: always
        expose:
          - 9001
          - 8082
        ports:
          - "${NGINX_LOCAL_PORT}:80"
        links:
          - php-fpm
        volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf/nginx.conf:cached
          - ./docker/nginx/conf/default.nginx:/etc/nginx/conf.d/default.conf:cached
          -  php-fpm:/var/run/php/:cached
          - ./:/var/www/html:cached
        networks:
          - equipmentscrm

    php-fpm:
        build: ./docker/php-fpm/
        container_name: php-fpm
        hostname: php-fpm
        restart: always
        volumes:
          - ./docker/php-fpm/php-fpm.conf:/etc/php/7.1/fpm/php-fpm.conf:cached
          - ./docker/php-fpm/php.ini:/etc/php/7.1/fpm/php.ini:cached
          - ./docker/php-fpm/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini:cached
          - ./docker/php-fpm/php-fpm.d/:/etc/php/7.1/fpm/pool.d/:cached
          - ./docker/php-fpm/supervisord.conf:/etc/supervisor/supervisord.conf:cached
          - ./docker/ssh:/root/.ssh/:cached
          - ./docker/frontend:/root/frontend/:cached
          - php-fpm:/var/run/php/:cached
          - ./:/var/www/html:cached
          #- $SSH_AUTH_SOCK:/ssh-agent
        environment:
          SSH_AUTH_SOCK: /ssh-agent
        networks:
          - equipmentscrm


volumes:
  php-fpm: {}

networks:
  equipmentscrm:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.1/16

