services:
  addhash.miner.panel.miner.list.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerListService
    public: true
    arguments: ['@addhash.miner.panel.user.authentication.get', '@addhash.miner.panel.miner.repository']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerListService: '@addhash.miner.panel.miner.list.service'

  App\AddHash\MinerPanel\Domain\Miner\Services\MinerListServiceInterface: '@addhash.miner.panel.miner.list.service'

  addhash.miner.panel.miner.get.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerGetService
    public: true
    arguments: ['@addhash.miner.panel.user.authentication.get', '@addhash.miner.panel.miner.repository', '@addhash.miner.panel.miner.summary.get.handler']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerGetService: '@addhash.miner.panel.miner.get.service'

  App\AddHash\MinerPanel\Domain\Miner\Services\MinerGetServiceInterface: '@addhash.miner.panel.miner.get.service'

  addhash.miner.panel.miner.create.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerCreateService
    public: true
    arguments: ['@addhash.miner.panel.user.authentication.get', '@addhash.miner.panel.miner.repository', '@addhash.miner.panel.miner.algorithm.repository', '@addhash.miner.panel.miner.type.repository', '@addhash.miner.panel.ip.check.service', '@addhash.miner.panel.miner.summary.get.handler']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerCreateService: '@addhash.miner.panel.miner.create.service'

  App\AddHash\MinerPanel\Domain\Miner\Services\MinerCreateServiceInterface: '@addhash.miner.panel.miner.create.service'

  addhash.miner.panel.miner.update.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerUpdateService
    public: true
    arguments: ['@addhash.miner.panel.user.authentication.get', '@addhash.miner.panel.miner.repository', '@addhash.miner.panel.miner.algorithm.repository', '@addhash.miner.panel.miner.type.repository', '@addhash.miner.panel.ip.check.service', '@addhash.miner.panel.miner.summary.get.handler']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerUpdateService: '@addhash.miner.panel.miner.update.service'

  App\AddHash\MinerPanel\Domain\Miner\Services\MinerUpdateServiceInterface: '@addhash.miner.panel.miner.update.service'

  addhash.miner.panel.miner.delete.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerDeleteService
    public: true
    arguments: ['@addhash.miner.panel.user.authentication.get', '@addhash.miner.panel.miner.repository']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerDeleteService: '@addhash.miner.panel.miner.delete.service'

  App\AddHash\MinerPanel\Domain\Miner\Services\MinerDeleteServiceInterface: '@addhash.miner.panel.miner.delete.service'

  addhash.miner.panel.miner.algorithm.list.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerAlgorithm\MinerAlgorithmListService
    public: true
    arguments: ['@addhash.miner.panel.miner.algorithm.repository']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerAlgorithm\MinerAlgorithmListService: '@addhash.miner.panel.miner.algorithm.list.service'

  App\AddHash\MinerPanel\Domain\Miner\MinerAlgorithm\Services\MinerAlgorithmListServiceInterface: '@addhash.miner.panel.miner.algorithm.list.service'

  addhash.miner.panel.miner.type.list.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerType\MinerTypeListService
    public: true
    arguments: ['@addhash.miner.panel.miner.type.repository']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerType\MinerTypeListService: '@addhash.miner.panel.miner.type.list.service'

  App\AddHash\MinerPanel\Domain\Miner\MinerType\Services\MinerTypeListServiceInterface: '@addhash.miner.panel.miner.type.list.service'

  addhash.miner.panel.miner.summary.get.service:
    class:  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerSummary\MinerSummaryGetService
    public: true
    arguments: ['@addhash.miner.panel.user.authentication.get', '@addhash.miner.panel.miner.repository', '@addhash.miner.panel.miner.summary.get.handler']
  App\AddHash\MinerPanel\Infrastructure\Services\Miner\MinerSummary\MinerSummaryGetService: '@addhash.miner.panel.miner.summary.get.service'

  App\AddHash\MinerPanel\Domain\Miner\MinerSummary\Services\MinerSummaryGetServiceInterface: '@addhash.miner.panel.miner.summary.get.service'

  addhash.miner.panel.miner.repository:
    class: App\AddHash\MinerPanel\Infrastructure\Repository\Miner\MinerRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\MinerPanel\Infrastructure\Repository\Miner\MinerRepository: '@addhash.miner.panel.miner.repository'

  App\AddHash\MinerPanel\Domain\Miner\Repository\MinerRepositoryInterface: '@addhash.miner.panel.miner.repository'

  addhash.miner.panel.miner.algorithm.repository:
    class: App\AddHash\MinerPanel\Infrastructure\Repository\Miner\MinerAlgorithmRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\MinerPanel\Infrastructure\Repository\Miner\MinerAlgorithmRepository: '@addhash.miner.panel.miner.algorithm.repository'

  App\AddHash\MinerPanel\Domain\Miner\MinerAlgorithm\Repository\MinerAlgorithmRepositoryInterface: '@addhash.miner.panel.miner.algorithm.repository'

  addhash.miner.panel.miner.type.repository:
    class: App\AddHash\MinerPanel\Infrastructure\Repository\Miner\MinerTypeRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\MinerPanel\Infrastructure\Repository\Miner\MinerTypeRepository: '@addhash.miner.panel.miner.type.repository'

  App\AddHash\MinerPanel\Domain\Miner\MinerType\Repository\MinerTypeRepositoryInterface: '@addhash.miner.panel.miner.type.repository'

  addhash.miner.panel.miner.summary.get.handler:
    class: App\AddHash\MinerPanel\Infrastructure\Miner\Summary\SummaryGetHandler
    public: true
    arguments: ['@addhash.cache']
  App\AddHash\MinerPanel\Infrastructure\Miner\Summary\SummaryGetHandler: '@addhash.miner.panel.miner.summary.get.handler'

  App\AddHash\MinerPanel\Domain\Miner\Summary\SummaryGetHandlerInterface: '@addhash.miner.panel.miner.summary.get.handler'