#index:
#    path: /
#    controller: App\Controller\DefaultController::index

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc/

addhash:
    resource: '../src/AddHash/Resources/routing'
    type: directory