index:
    path: /api/doc
    controller: App\Addhash\AdminPanel\Application\Controller\AppController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /

api_login_check:
    path: /api/login_check

addhash:
    resource: '../src/AddHash/Resources/routing'
    type: directory