index:
    path: /api/doc
#    controller: App\Controller\DefaultController::index

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /

addhash:
    resource: '../src/AddHash/Resources/routing'
    type: directory