services:

  ##AddHash Store Category
  addhash.store.category.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Store\Category\StoreCategoryDQLRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Store\Category\StoreCategoryDQLRepository: '@addhash.store.category.repository'

  App\AddHash\AdminPanel\Domain\Store\Category\Model\Store_Category\CategoryRepositoryInterface: '@addhash.store.category.repository'

  addhash.store.category.list.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Category\ListService
    public: true
    arguments: ['@addhash.store.category.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Category\ListService: '@addhash.store.category.list.service'

  App\AddHash\AdminPanel\Domain\Store\Category\Services\ListServiceInterface: '@addhash.store.category.list.service'

  ##AddHash User Service
  addhash.user.register.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\UserRegisterService
    public: true
    arguments: ['@addhash.user.repository', '@security.encoder_factory']
  App\AddHash\AdminPanel\Infrastructure\Services\User\UserRegisterService: '@addhash.user.register.service'

  App\AddHash\AdminPanel\Domain\User\Services\UserRegisterServiceInterface: '@addhash.user.register.service'

