services:

  addhash.store.order.event.subscriber:
      class: App\AddHash\AdminPanel\Infrastructure\EventSubscribers\Store\Order\StoreOrderEventSubscriber
      tags:
          - { name: kernel.event_subscriber, event: store.order.payed }

  App\AddHash\AdminPanel\Application\ConsoleCommand\CreateOrderClearCommand:
      public: false
      arguments: ['@addhash.store.order.un.reserve.miner.service']
      tags: ['console.command']

  App\AddHash\AdminPanel\Application\ConsoleCommand\ProcessSchedulerTask:
      public: false
      arguments: ['@addhash.scheduler.task.worker.service']
      tags: ['console.command']

imports:

  ## User Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/User/Resources/config/services.yaml"}

  ## Wallet Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Wallet/Resources/config/services.yaml"}

  ## Store Order Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Store/Order/Resources/config/services.yaml"}

  ## Store Product Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Store/Product/Resources/config/services.yaml"}

  ## Srore.Category Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Store/Category/Resources/config/services.yaml"}

  ## Miner Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Miner/Resources/config/services.yaml"}

  ## Payment Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Payment/Resources/config/services.yaml"}

  ## Scheduler Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Scheduler/Task/Resources/config/services.yaml"}

  ## PromoContact Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/PromoContact/Resources/config/services.yaml"}

  ## Info Services ##
  - { resource: "../../../AddHash/AdminPanel/Application/DependencyInjection/Info/Resources/config/services.yaml"}

  ## Authentication ##
  - { resource: "../../../AddHash/Authentication/Application/DependencyInjection/Resources/config/services.yaml"}