services:

  ##AddHash Store Category
  addhash.store.category.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Store\Category\StoreCategoryRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Store\Category\StoreCategoryRepository: '@addhash.store.category.repository'

  addhash.store.product.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Store\Product\StoreProductRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Store\Product\StoreProductRepository: '@addhash.store.product.repository'

  App\AddHash\AdminPanel\Domain\Store\Category\Model\Store_Category\CategoryRepositoryInterface: '@addhash.store.category.repository'

  addhash.store.order.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Store\Order\StoreOrderRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Store\Order\StoreOrderRepository: '@addhash.store.order.repository'

  App\AddHash\AdminPanel\Domain\Store\Order\OrderRepositoryInterface: '@addhash.store.order.repository'

  addhash.store.order.item.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Store\Order\Item\StoreOrderItemRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Store\Order\Item\StoreOrderItemRepository: '@addhash.store.order.item.repository'

  App\AddHash\AdminPanel\Domain\Store\Order\Item\StoreOrderItemRepositoryInterface: '@addhash.store.order.item.repository'

  addhash.miner.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerRepository: '@addhash.miner.repository'

  App\AddHash\AdminPanel\Domain\Miners\Repository\MinerRepositoryInterface: '@addhash.miner.repository'

  addhash.store.category.list.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Category\ListService
    public: true
    arguments: ['@addhash.store.category.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Category\ListService: '@addhash.store.category.list.service'

  App\AddHash\AdminPanel\Domain\Store\Category\Services\ListServiceInterface: '@addhash.store.category.list.service'

  addhash.store.admin.category.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Category\CreateService
    public: true
    arguments: ['@addhash.store.category.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Category\CreateService: '@addhash.store.admin.category.create.service'

  App\AddHash\AdminPanel\Domain\Store\Category\Services\CreateServiceInterface: '@addhash.store.admin.category.create.service'

  addhash.store.product.list.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Product\StoreProductListService
    public: true
    arguments: ['@addhash.store.product.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Product\StoreProductListService: '@addhash.store.product.list.service'

  App\AddHash\AdminPanel\Domain\Store\Product\Services\StoreProductListServiceInterface: '@addhash.store.product.list.service'

  addhash.store.product.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Product\StoreProductCreateService
    public: true
    arguments: ['@addhash.store.product.repository', '@addhash.store.category.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Product\StoreProductCreateService: '@addhash.store.product.create.service'

  App\AddHash\AdminPanel\Domain\Store\Product\Services\StoreProductCreateServiceInterface: '@addhash.store.product.create.service'

  addhash.store.order.create.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Order\StoreOrderCreateService
    public: true
    arguments: ['@addhash.store.product.repository','@addhash.store.order.repository','@addhash.store.order.item.repository', '@security.token_storage', '@addhash.miner.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Order\StoreOrderCreateService: '@addhash.store.order.create.service'

  App\AddHash\AdminPanel\Domain\Store\Order\Services\StoreOrderCreateServiceInterface: '@addhash.store.order.create.service'


  addhash.store.order.get.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Order\StoreOrderGetService
    public: true
    arguments: ['@addhash.store.order.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Order\StoreOrderGetService: '@addhash.store.order.get.service'

  App\AddHash\AdminPanel\Domain\Store\Order\Services\StoreOrderGetServiceInterface: '@addhash.store.order.get.service'

  addhash.payment.repository:
      class: App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentRepository
      public: true
      arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentRepository: '@addhash.payment.repository'

  addhash.payment.transaction.repository:
      class: App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentTransactionRepository
      public: true
      arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentTransactionRepository: '@addhash.payment.transaction.repository'

  addhash.payment.order.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Payment\MakePaymentForOrderService
    public: true
    arguments: ['@addhash.payment.repository', '@addhash.payment.transaction.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Payment\MakePaymentForOrderService: '@addhash.payment.order.service'

  addhash.store.order.checkout.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Store\Order\StoreOrderCheckoutService
    public: true
    arguments: ['@addhash.store.order.repository', '@addhash.payment.order.service']
  App\AddHash\AdminPanel\Infrastructure\Services\Store\Order\StoreOrderCheckoutService: '@addhash.store.order.checkout.service'

  App\AddHash\AdminPanel\Domain\Store\Order\Services\StoreOrderCheckoutServiceInterface: '@addhash.store.order.checkout.service'

  ##AddHash User Service
  addhash.user.register.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\User\UserRegisterService
    public: true
    arguments: ['@addhash.user.repository', '@security.encoder_factory']
  App\AddHash\AdminPanel\Infrastructure\Services\User\UserRegisterService: '@addhash.user.register.service'

  App\AddHash\AdminPanel\Domain\User\Services\UserRegisterServiceInterface: '@addhash.user.register.service'

