services:
  addhash.captcha.cache:
    class: App\AddHash\AdminPanel\Infrastructure\Captcha\CaptchaCache
    public: true
    arguments: ['@addhash.cache']
  App\AddHash\AdminPanel\Infrastructure\Captcha\CaptchaCache: '@addhash.captcha.cache'

  App\AddHash\AdminPanel\Domain\Captcha\CaptchaCacheInterface: '@addhash.captcha.cache'

  addhash.re.captcha:
    class: App\AddHash\AdminPanel\Infrastructure\Captcha\ReCaptcha\ReCaptcha
    public: true
    arguments: []
  App\AddHash\AdminPanel\Infrastructure\Captcha\ReCaptcha\ReCaptcha: '@addhash.re.captcha'

  App\AddHash\AdminPanel\Domain\Captcha\ReCaptcha\ReCaptchaInterface: '@addhash.re.captcha'

  addhash.re.captcha.service:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Captcha\ReCaptcha\ReCaptchaService
    public: true
    arguments: ['@request_stack', '@addhash.captcha.cache', '@addhash.re.captcha']
  App\AddHash\AdminPanel\Infrastructure\Services\Captcha\ReCaptcha\ReCaptchaService: '@addhash.re.captcha.service'

  App\AddHash\AdminPanel\Domain\Captcha\Services\ReCaptcha\ReCaptchaServiceInterface: '@addhash.re.captcha.service'