services:

  addhash.payment.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentRepository: '@addhash.payment.repository'

  App\AddHash\AdminPanel\Domain\Payment\PaymentInterface: '@addhash.payment.repository'

  addhash.payment.transaction.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentTransactionRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentTransactionRepository: '@addhash.payment.transaction.repository'

  App\AddHash\AdminPanel\Domain\Payment\Repository\PaymentTransactionRepositoryInterface: '@addhash.payment.transaction.repository'

  addhash.payment.method.repository:
    class: App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentMethodRepository
    public: true
    arguments: ['@doctrine.orm.entity_manager']
  App\AddHash\AdminPanel\Infrastructure\Repository\Payment\PaymentMethodRepository: '@addhash.payment.method.repository'

  App\AddHash\AdminPanel\Domain\Payment\Repository\PaymentMethodRepositoryInterface: '@addhash.payment.method.repository'

  addhash.order.checkout.payment.service:
    class:  App\AddHash\AdminPanel\Infrastructure\Services\Payment\MakePaymentForOrderService
    public: true
    arguments: ['@addhash.payment.repository', '@addhash.payment.method.repository', '@addhash.payment.transaction.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Payment\MakePaymentForOrderService: '@addhash.order.checkout.payment.service'

  App\AddHash\AdminPanel\Domain\Payment\Services\MakePaymentForOrderServiceInterface: '@addhash.order.checkout.payment.service'

  addhash.payment.crypto.service:
    class:  App\AddHash\AdminPanel\Infrastructure\Services\Payment\MakeCryptoPaymentService
    public: true
    arguments: ['@addhash.payment.repository', '@addhash.payment.method.repository', '@addhash.payment.transaction.repository', '@addhash.store.order.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Payment\MakeCryptoPaymentService: '@addhash.order.checkout.payment.service'

  App\AddHash\AdminPanel\Domain\Payment\Services\MakeCryptoPaymentServiceInterface: '@addhash.payment.crypto.service'

  addhash.payment.crypto.currencies:
    class: App\AddHash\AdminPanel\Infrastructure\Services\Payment\GetCryptoCurrenciesService
    public: true
  App\AddHash\AdminPanel\Infrastructure\Services\Payment\GetCryptoCurrenciesService: '@addhash.payment.crypto.currencies'

  App\AddHash\AdminPanel\Domain\Payment\Services\GetCryptoCurrenciesServiceInterface: '@addhash.payment.crypto.currencies'

  addhash.payment.crypto.callback.service:
    class:  App\AddHash\AdminPanel\Infrastructure\Services\Payment\CallbackCryptoPaymentService
    public: true
    arguments: ['@addhash.store.order.repository', '@addhash.payment.transaction.repository']
  App\AddHash\AdminPanel\Infrastructure\Services\Payment\CallbackCryptoPaymentService: '@addhash.payment.crypto.callback.service'

  App\AddHash\AdminPanel\Domain\Payment\Services\CallbackCryptoPaymentServiceInterface: '@addhash.payment.crypto.callback.service'
