user.register:
  path: "/api/v1/user/register"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\UserController::register

store.category.list:
    path: "/api/v1/store/categories"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::index

store.category.get:
    path: "/api/v1/store/categories/{id}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::get

store.product.list:
    path: "/api/v1/store/products"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::index

store.product.get:
    path: "/api/v1/store/products/{id}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::get

store.order.create:
    path: "/api/v1/store/order"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::create

store.order.addProduct:
    path: "/api/v1/store/order/addProduct"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::addProduct

store.order.removeItem:
    path: "/api/v1/store/order/removeItem/{id}"
    methods: DELETE
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::removeItem

store.order.get:
    path: "/api/v1/store/order"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::get

store.order.prepare.checkout:
    path: "/api/v1/store/order/checkout/prepare"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::prepareCheckout

store.order.checkout:
    path: "/api/v1/store/order/checkout"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::checkout

admin.store.category.create:
    path: "/api/v1/admin/store/category/create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::create

admin.store.product.create:
    path: "/api/v1/admin/store/product/create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::create

account.settings.general.information.update:
    path: "/api/v1/user/account/settings/information"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\GeneralInformationController::update

account.settings.general.information.get:
    path: "/api/v1/user/account/settings/information"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\GeneralInformationController::get

account.settings.password.update:
    path: "/api/v1/user/account/settings/password"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\PasswordController::update

account.settings.wallet.update:
    path: "/api/v1/user/account/settings/wallets"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::update

account.settings.wallet.get:
    path: "/api/v1/user/account/settings/wallets"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::get

account.settings.wallet.create:
    path: "/api/v1/user/account/settings/wallets"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::create

store.product.vote:
    path: "/api/v1/store/product/vote"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::createVote

user.miner.control.get:
  path: "/api/v1/user/miner/control"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\MinerControlController::get

user.miner.test.query:
  path: "/api/v1/user/miner/test/query"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\MinerControlController::testQueryMiner