user.register:
  path: "/api/v1/user.register"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\UserController::register

store.category.list:
    path: "/api/v1/store.category.list"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::index

store.category.get:
    path: "/api/v1/store.category.get/{id}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::get

store.product.list:
    path: "/api/v1/store.product.list"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::index

store.product.get:
    path: "/api/v1/store.product.get/{id}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::get

store.order.create:
    path: "/api/v1/store.order.create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::create

store.order.get:
    path: "/api/v1/store.order.get"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::get

admin.store.category.create:
    path: "/api/v1/admin.store.category.create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::create

admin.store.product.create:
    path: "/api/v1/admin.store.product.create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::create