info.currencies:
    path: "/api/v1/info/currencies"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\InfoController::getCryptoCurrencies

user.register:
    path: "/api/v1/user/register"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\User\UserController::create

user.password.reset:
    path: "/api/v1/user/password/reset"
    methods: POST
    controller: App\AddHash\Authentication\Application\Controller\PasswordRecoveryController::sendEmailToResetPassword

user.password.recovery:
    path: "/api/v1/user/password/recovery"
    methods: POST
    controller: App\AddHash\Authentication\Application\Controller\PasswordRecoveryController::recoveryPassword

user.password.recovery.chech.hash:
    path: "/api/v1/user/password/recovery/hash"
    methods: POST
    controller: App\AddHash\Authentication\Application\Controller\PasswordRecoveryController::checkRecoveryHash

store.category.list:
    path: "/api/v1/store/categories"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::index

store.category.get:
    path: "/api/v1/store/categories/{id}"
    requirements:
        id: '\d+'
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::get

store.product.list:
    path: "/api/v1/store/products"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::index

store.product.get:
    path: "/api/v1/store/products/{id}"
    requirements:
        id: '\d+'
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::get

store.order.create:
    path: "/api/v1/store/order"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::create

store.order.addProduct:
    path: "/api/v1/store/order/addProduct"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::addProduct

store.order.removeItem:
    path: "/api/v1/store/order/removeItem/{id}"
    requirements:
        id: '\d+'
    methods: DELETE
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::removeItem

store.order.get:
    path: "/api/v1/store/order"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::get

store.order.prepare.checkout:
    path: "/api/v1/store/order/checkout/prepare"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::prepareCheckout

store.order.checkout:
    path: "/api/v1/store/order/checkout"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::checkout

payments.crypto:
    path: "/api/v1/payments/crypto/new/{orderId}/{currency}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::createNewPayment

payments.crypto.currencies:
    path: "/api/v1/payments/crypto/currencies/{orderId}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::getCurrencies

payments.crypto.state:
    path: "/api/v1/payments/crypto/state/{orderId}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::getState

payments.crypto.callback:
    path: "/api/v1/payments/crypto/callback/{orderId}"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::callback

admin.store.category.create:
    path: "/api/v1/admin/store/category/create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::create

admin.store.product.create:
    path: "/api/v1/admin/store/product/create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::create

account.settings.general.information.update:
    path: "/api/v1/user/account/settings/information"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\GeneralInformationController::update

account.settings.general.information.get:
    path: "/api/v1/user/account/settings/information"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\GeneralInformationController::get

account.settings.password.update:
    path: "/api/v1/user/account/settings/password"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\PasswordController::update

account.settings.wallet.update:
    path: "/api/v1/user/account/settings/wallets"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::update

account.settings.wallet.get:
    path: "/api/v1/user/account/settings/wallets"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::get

account.settings.wallet.create:
    path: "/api/v1/user/account/settings/wallets"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::create

store.product.vote:
    path: "/api/v1/store/product/vote"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::createVote

user.miner.control.get:
  path: "/api/v1/user/miners"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\MinerControlController::get

user.miner.control.pools.get:
  path: "/api/v1/user/miners/{id}/pools"
  requirements:
      id: '\d+'
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::get

user.miner.control.pools.create:
  path: "/api/v1/user/miners/{id}/pools"
  requirements:
      id: '\d+'
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::create

user.order.history.list:
  path: "/api/v1/user/orders"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Order\History\UserOrderHistoryController::index

user.order.history.get:
  path: "/api/v1/user/orders/{id}"
  requirements:
      id: '\d+'
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Order\History\UserOrderHistoryController::get

wallet.type.list:
  path: "/api/v1/wallet/types"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\WalletTypeController::index

promo.contact.create:
  path: "/api/v1/promo/contact"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\PromoContactController::create

user.miner.control.rig.index:
  path: "/api/v1/user/miners/rigs"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::index

user.miner.control.rig.get:
  path: "/api/v1/user/miners/rigs/{id}"
  requirements:
      id: '\d+'
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::get

user.miner.control.rig.create:
  path: "/api/v1/user/miners/rigs"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::create

user.miner.control.rig.update:
  path: "/api/v1/user/miners/rigs/{id}"
  requirements:
      id: '\d+'
  methods: PUT
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::update

user.miner.control.rig.delete:
  path: "/api/v1/user/miners/rigs/{id}"
  requirements:
      id: '\d+'
  methods: DELETE
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::delete

user.notifications:
  path: "/api/v1/user/notifications"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Notification\UserNotificationController::getNewNotifications

user.notifications.markAsRead:
  path: "/api/v1/user/notifications"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\Notification\UserNotificationController::markAsRead

public.information.re.captcha.key.get:
  path: "/api/v1/info/recaptcha"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\PublicInformationController::getPublicKeyReCaptcha


miner.panel.miner.index:
  path: "/api/v1/miner/panel/miners"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerController::index

miner.panel.miner.get:
  path: "/api/v1/miner/panel/miners/{id}"
  requirements:
      id: '\d+'
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerController::get

miner.panel.miner.create:
  path: "/api/v1/miner/panel/miners"
  methods: POST
  controller: App\AddHash\MinerPanel\Application\Controller\MinerController::create

miner.panel.miner.update:
  path: "/api/v1/miner/panel/miners/{id}"
  requirements:
    id: '\d+'
  methods: PUT
  controller: App\AddHash\MinerPanel\Application\Controller\MinerController::update

miner.panel.miner.delete:
  path: "/api/v1/miner/panel/miners/{id}"
  requirements:
    id: '\d+'
  methods: DELETE
  controller: App\AddHash\MinerPanel\Application\Controller\MinerController::delete

miner.panel.miner.all:
  path: "/api/v1/miner/panel/miners/list"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerController::all

miner.panel.miner.check.ip.address:
  path: "/api/v1/miner/panel/ip/validate"
  methods: POST
  controller: App\AddHash\MinerPanel\Application\Controller\IpAddressController::check

miner.panel.miner.algorithm.all:
  path: "/api/v1/miner/panel/miners/algorithms/list"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerAlgorithmController::all

miner.panel.miner.type.all:
  path: "/api/v1/miner/panel/miners/types/list"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerTypeController::all

miner.panel.miner.summary.get:
  path: "/api/v1/miner/panel/miners/{id}/summary/"
  requirements:
    id: '\d+'
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerSummaryController::get

miner.panel.miner.pool.get:
  path: "/api/v1/miner/panel/miners/{id}/pools/"
  requirements:
    id: '\d+'
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerPoolController::get

miner.panel.miner.coin.get:
  path: "/api/v1/miner/panel/miners/{id}/coins/"
  requirements:
    id: '\d+'
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerCoinController::get

miner.panel.miner.coin.index:
  path: "/api/v1/miner/panel/miners/coins/"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\MinerCoinController::index

miner.panel.rig.index:
  path: "/api/v1/miner/panel/rigs"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\RigController::index

miner.panel.rig.get:
  path: "/api/v1/miner/panel/rigs/{id}"
  requirements:
    id: '\d+'
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\RigController::get

miner.panel.rig.create:
  path: "/api/v1/miner/panel/rigs"
  methods: POST
  controller: App\AddHash\MinerPanel\Application\Controller\RigController::create

miner.panel.rig.update:
  path: "/api/v1/miner/panel/rigs/{id}"
  requirements:
    id: '\d+'
  methods: PUT
  controller: App\AddHash\MinerPanel\Application\Controller\RigController::update

miner.panel.rig.delete:
  path: "/api/v1/miner/panel/rigs/{id}"
  requirements:
    id: '\d+'
  methods: DELETE
  controller: App\AddHash\MinerPanel\Application\Controller\RigController::delete

miner.panel.rig.all:
  path: "/api/v1/miner/panel/rigs/list"
  methods: GET
  controller: App\AddHash\MinerPanel\Application\Controller\RigController::all