info.currencies:
  path: "/api/v1/info/currencies"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\InfoController::getCryptoCurrencies

user.register:
  path: "/api/v1/user/register"
  methods: POST
  controller: App\AddHash\Authentication\Application\Controller\UserController::register

user.password.reset:
  path: "/api/v1/user/password/reset"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\PasswordRecoveryController::sendEmailToResetPassword

user.password.recovery:
  path: "/api/v1/user/password/recovery"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\PasswordRecoveryController::recoveryPassword

user.password.recovery.chechhash:
  path: "/api/v1/user/password/recovery/hash"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\PasswordRecoveryController::checkRecoveryHash

store.category.list:
    path: "/api/v1/store/categories"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::index

store.category.get:
    path: "/api/v1/store/categories/{id}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::get

store.product.list:
    path: "/api/v1/store/products"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::index

store.product.get:
    path: "/api/v1/store/products/{id}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::get

store.order.create:
    path: "/api/v1/store/order"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::create

store.order.addProduct:
    path: "/api/v1/store/order/addProduct"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::addProduct

store.order.removeItem:
    path: "/api/v1/store/order/removeItem/{id}"
    methods: DELETE
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::removeItem

store.order.get:
    path: "/api/v1/store/order"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::get

store.order.prepare.checkout:
    path: "/api/v1/store/order/checkout/prepare"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::prepareCheckout

store.order.checkout:
    path: "/api/v1/store/order/checkout"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreOrderController::checkout

payments.crypto:
    path: "/api/v1/payments/crypto/new/{orderId}/{currency}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::createNewPayment

payments.crypto.currencies:
    path: "/api/v1/payments/crypto/currencies/{orderId}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::getCurrencies

payments.crypto.state:
    path: "/api/v1/payments/crypto/state/{orderId}"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::getState

payments.crypto.callback:
    path: "/api/v1/payments/crypto/callback/{orderId}"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\Payments\CryptoPaymentsController::callback

admin.store.category.create:
    path: "/api/v1/admin/store/category/create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreCategoryController::create

admin.store.product.create:
    path: "/api/v1/admin/store/product/create"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::create

account.settings.general.information.update:
    path: "/api/v1/user/account/settings/information"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\GeneralInformationController::update

account.settings.general.information.get:
    path: "/api/v1/user/account/settings/information"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\GeneralInformationController::get

account.settings.password.update:
    path: "/api/v1/user/account/settings/password"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\PasswordController::update

account.settings.wallet.update:
    path: "/api/v1/user/account/settings/wallets"
    methods: PUT
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::update

account.settings.wallet.get:
    path: "/api/v1/user/account/settings/wallets"
    methods: GET
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::get

account.settings.wallet.create:
    path: "/api/v1/user/account/settings/wallets"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\User\AccountSettings\WalletController::create

store.product.vote:
    path: "/api/v1/store/product/vote"
    methods: POST
    controller: App\AddHash\AdminPanel\Application\Controller\StoreProductController::createVote

user.miner.control.get:
  path: "/api/v1/user/miners"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\MinerControlController::get

user.miner.control.pools.get:
  path: "/api/v1/user/miners/{id}/pools"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::get

user.miner.control.pools.create:
  path: "/api/v1/user/miners/{id}/pools"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::create

user.miner.control.pools.delete:
  path: "/api/v1/user/miners/{id}/pools"
  methods: DELETE
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::delete

user.miner.control.pools.update:
  path: "/api/v1/user/miners/{id}/pools"
  methods: PUT
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::update

user.miner.control.pools.status.update:
  path: "/api/v1/user/miners/{id}/pools/status"
  methods: PUT
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Pool\UserMinerControlPoolController::statusUpdate

user.order.history.list:
  path: "/api/v1/user/orders"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Order\History\UserOrderHistoryController::index

user.order.history.get:
  path: "/api/v1/user/orders/{id}"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Order\History\UserOrderHistoryController::get

wallet.type.list:
  path: "/api/v1/wallet/types"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\WalletTypeController::index

promo.contact.create:
  path: "/api/v1/promo/contact"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\PromoContactController::create

user.miner.control.rig.index:
  path: "/api/v1/user/miners/rigs"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::index

user.miner.control.rig.get:
  path: "/api/v1/user/miners/rigs/{id}"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::get

user.miner.control.rig.create:
  path: "/api/v1/user/miners/rigs"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::create

user.miner.control.rig.update:
  path: "/api/v1/user/miners/rigs/{id}"
  methods: PUT
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::update

user.miner.control.rig.delete:
  path: "/api/v1/user/miners/rigs/{id}"
  methods: DELETE
  controller: App\AddHash\AdminPanel\Application\Controller\User\Miner\Rig\UserMinerControlRigController::delete

user.notifications:
  path: "/api/v1/user/notifications"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\Notification\UserNotificationController::getNewNotifications

user.notifications.markAsRead:
  path: "/api/v1/user/notifications"
  methods: POST
  controller: App\AddHash\AdminPanel\Application\Controller\User\Notification\UserNotificationController::markAsRead

public.information.re.captcha.key.get:
  path: "/api/v1/info/recaptcha"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\PublicInformationController::getPublicKeyReCaptcha

user.miner.test.query:
  path: "/api/v1/user/miner/test/query"
  methods: GET
  controller: App\AddHash\AdminPanel\Application\Controller\User\MinerControlController::testQueryMiner