services:
  addhash.authentication.open.host:
    class: App\AddHash\Authentication\Infrastructure\OpenHost\AuthenticationOpenHost
    public: true
    arguments: ['@security.token_storage','@addhash.user.register.service', '@validator']
  App\AddHash\Authentication\Infrastructure\OpenHost\AuthenticationOpenHost: '@addhash.authentication.open.host'

  App\AddHash\Authentication\Domain\OpenHost\AuthenticationOpenHostInterface: '@addhash.authentication.open.host'