services:
    addhash.miner.repository:
      class: App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerRepository
      public: true
      arguments: ['@doctrine.orm.entity_manager']
    App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerRepository: '@addhash.miner.repository'

    App\AddHash\AdminPanel\Domain\Miners\Repository\MinerRepositoryInterface: '@addhash.miner.repository'

    addhash.miner.stock.repository:
      class: App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerStockRepository
      public: true
      arguments: ['@doctrine.orm.entity_manager']
    App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerStockRepository: '@addhash.miner.stock.repository'

    App\AddHash\AdminPanel\Domain\Miners\Repository\MinerStockRepositoryInterface: '@addhash.miner.stock.repository'

    addhash.miner.allowed.url.repository:
      class: App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerAllowedUrlRepository
      public: true
      arguments: ['@doctrine.orm.entity_manager']
    App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerAllowedUrlRepository: '@addhash.miner.allowed.url.repository'

    App\AddHash\AdminPanel\Domain\Miners\Repository\MinerAllowedUrlRepositoryInterface: '@addhash.miner.allowed.url.repository'

    addhash.miner.stock.pool.repository:
      class: App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerStockPoolRepository
      public: true
      arguments: ['@doctrine.orm.entity_manager']
    App\AddHash\AdminPanel\Infrastructure\Repository\Miner\MinerStockPoolRepository: '@addhash.miner.stock.pool.repository'

    App\AddHash\AdminPanel\Domain\Miners\Repository\MinerStockPoolRepositoryInterface: '@addhash.miner.stock.pool.repository'